#!/bin/bash

. ./common_funcs

# Exits if chrome has been installed
google-chrome-stable --version &> /dev/null && check_installed "chrome"

# Adds the repo
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update

# Installs chrome
sudo apt-get -y install google-chrome-stable

# Modifies google-chrome.list in /etc/apt/sources.list.d to avoid repeated configuration
sudo cp google-chrome.list /etc/apt/sources.list.d/google-chrome.list

google-chrome-stable --version &> /dev/null && log_append "chrome installed" || log_append "failed to install chrome"
