#!/bin/bash

. ./common_funcs

# Exits if vim has been installed
vim --version &> /dev/null && check_installed "vim"

# Removes some vim components (needed for ubuntu >= 19.10)
sudo apt-get remove -y --purge vim-common vim-tiny

# Installs vim
sudo apt-get -y install vim

vim --version &> /dev/null && log_append "vim installed" || log_append "failed to install vim"
