#!/bin/bash

# Adds the repo
echo "" | wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
sudo apt-get update

# Installation
sudo apt-get -y install atom

atom --version > dev/null && echo "atom installed" >> $LOG || echo "failed to install atom" >> $LOG
