#!/bin/bash

# Adds the repo
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update

# Installation
sudo apt-get -y install google-chrome-stable

google-chrome-stable --version && echo "chrome installed" >> $LOG || echo "failed to install chrome" >> $LOG
