#!/bin/bash

# Enters /Downloads
cd /home/*/Downloads

# Downloads the package
wget http://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/3.0.1/baidunetdisk_linux_3.0.1.2.deb

# Installation
sudo dpkg -i baidunetdisk*
