#!/bin/bash

. ./log_append

# Exits if pycharm has been installed
[ -e /opt/pycharm* ] && exit 0

DIR=`pwd`

# Downloads the pycharm package
cd /home/`whoami`/Downloads
wget https://download.jetbrains.8686c.com/python/pycharm-community-2019.3.1.tar.gz
# Extracts files to /opt
sudo tar -zxvf pycharm-community*tar* -C /opt

# Installs pycharm
cd /opt/pycharm-community*/bin
echo -e "\a"
sudo ./pycharm.sh

# Makes the icon be able to be added to favorites
cd /usr/share/applications
sudo touch jetbrains-pycharm-ce.desktop
sudo chmod 777 jetbrains-pycharm-ce.desktop
sudo echo "[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community Edition
Icon=/opt/pycharm-community-2019.3.1/bin/pycharm.svg
Exec="/opt/pycharm-community-2019.3.1/bin/pycharm.sh" %f
Comment=Python IDE for Professional Developers
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm-ce" >> jetbrains-pycharm-ce.desktop

# Removes the package if pycharm is successfully installed
[ $? -eq 0 ] && rm -f /home/`whoami`/Downloads/pycharm*

cd $DIR

[ $? -eq 0 ] && log_append "pycharm installed" || log_append "failed to install pycharm"
