#!/bin/bash

. ./log_append

# Adds the repo
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update

# Installs chrome
sudo apt-get -y install google-chrome-stable

google-chrome-stable --version && log_append "chrome installed" || log_append "failed to install chrome"
