#!/bin/bash

# Enters /Downloads
cd /home/*/Downloads

# Downloads the package
wget http://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/3.0.1/baidunetdisk_linux_3.0.1.2.deb

# Installation
sudo dpkg -i baidunetdisk*

# Removes the package if baidu netdisk is successfully installed
dpkg -l | grep baidunetdisk && rm -f /home/*/Downloads/baidunetdisk*

[ $? -eq 0 ] && echo "baidu net disk installed" >> $LOG || echo "failed to install baidu net disk" >> $LOG
