#!/bin/bash

. ./log_append

pip3_install() {
	pip3 install --default-timeout 60 --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple/ $1
	python3 -c "import $2" && log_append "$1 installed" || log_append "failed to install $1"
}

# tensorflow
pip3_install tensorflow tensorflow

# numpy
pip3_install numpy numpy

# matplotlib
pip3_install matplotlib matplotlib

# pandas
pip3_install pandas pandas

# scipy
pip3_install scipy scipy

# scikit-learn
pip3_install scikit-learn sklearn

# jupyter
pip3_install jupyter jupyter

# opencv
pip3_install opencv-python cv2

# baidu-aip
pip3_install baidu-aip aip

# bs4
pip3_install bs4 bs4

# selenium
pip3_install selenium selenium

# lxml
pip3_install lxml lxml

# itchat
pip3_install itchat itchat

# pdf2image
pip3_install pdf2image pdf2image

# tkinter
sudo apt-get install -y python3-tk
python3 -c "import tkinter" && log_append "tkinter installed" || log_append "failed to install tkinter"
