#!/bin/bash

. ./common_funcs

# Exits if onedrive has been installed
onedrive --version &> /dev/null && check_installed "onedrive"

DIR=`pwd`

# Installs dlang
sudo curl -fsS https://dlang.org/install.sh | bash -s dmd
sudo mv ~/dlang /opt

cd /opt

# Activates DMD
source dlang/dmd-*/activate

# Clones the repo
sudo git clone https://github.com/abraunegg/onedrive.git
cd onedrive

# Installs onedrive
sudo ./configure
sudo make clean
sudo make
sudo make install

# Deactivates DMD
deactivate

# Automatic update
systemctl --user enable onedrive
systemctl --user start onedrive

cd $DIR

onedrive --version &> /dev/null && log_append "onedrive installed" || log_append "failed to install onedrive"
