#!/bin/bash

# Installs necessary dependencies
cd /opt
sudo apt -y install libcurl4-openssl-dev libsqlite3-dev
sudo snap install --classic dmd && sudo snap install --classic dub

# Clones the repo
sudo git clone https://github.com/skilion/onedrive.git
cd onedrive

# Compiles
sudo make
sudo make install

# Initializes onedrive
echo -e "\a"
onedrive
