#!/bin/bash

. ./common_funcs

# Exits if git has been installed
git --version &> /dev/null && check_installed "git"

# Installs ffmpeg
sudo apt-get -y install git

git --version &> /dev/null && log_append "git installed" || log_append "failed to install git"
