#!/bin/bash

# Adds the repo
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update

# Installation
sudo apt-get -y install typora

dpkg -l | grep typora && echo "typora installed" >> $LOG || echo "failed to install typora" >> $LOG
