#!/bin/bash

. ./log_append

DIR=`pwd`

# Downloads the vmware package
cd /home/`whoami`/Downloads
wget https://download3.vmware.com/software/wkst/file/VMware-Workstation-Full-15.5.1-15018445.x86_64.bundle

# Enables the bundle package to be executed
chmod +x VMware*
# Executes the bundle package
sudo ./VMware* --console --eulas-agreed --required

# Removes the package if vmware is successfully installed
[ $? -eq 0 ] && rm -f VMware*

cd $DIR

[ $? -eq 0 ] && log-append "vmware installed" || log_append "failed to install pycharm"
