#!/bin/bash

# dash -> bash
sudo dpkg-reconfigure dash

# Removes games
sudo apt-get -y --purge remove aisleriot gnome-mahjongg gnome-mines gnome-sudoku libgnome-games-support-1-3:amd64 libgnome-games-support-common

# Changes the sources
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bcakup
sudo sh -c "cat sources > /etc/apt/sources.list"
sudo apt-get update
sudo apt-get -y upgrade















f() {
script_list_1=(install_vim install_pip3 install_git install_make)
for i in ${script_list_1[@]}
do
{
 	sh $i 2> $i"_err" && echo "$i done" >> install_log

}
done

sudo apt-get update

script_list_2=(install_chrome install_baidu_net_disk install_pycharm install_atom install_onedrive)
for i in ${script_list_2[@]}
do
{
	sh $i 2> $i"_err" && echo "$i done" >> install_log
}
done
}
