#!/bin/bash

. ./common_funcs

# Exits if baidu netdisk has been downloaded
dpkg -l | grep baidunetdisk &> /dev/null && check_installed "baidu netdisk"

DIR=`pwd`

# Downloads the package
cd ~/Downloads
wget http://issuecdn.baidupcs.com/issue/netdisk/LinuxGuanjia/3.0.1/baidunetdisk_linux_3.0.1.2.deb

# Installs baidu netdisk
sudo dpkg -i baidunetdisk*

# Removes the package if baidu netdisk is successfully installed
dpkg -l | grep baidunetdisk &> /dev/null && rm -f baidunetdisk*

cd $DIR

dpkg -l | grep baidunetdisk &> /dev/null && log_append "baidu net disk installed" || log_append "failed to install baidu net disk"
